# Generated by Django 4.0.2 on 2023-02-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('category_description', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('city_state', models.CharField(default='U.T.', max_length=255)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=80)),
                ('store_email', models.EmailField(max_length=254)),
                ('store_mobile', models.CharField(max_length=20)),
                ('store_password', models.CharField(max_length=50)),
                ('store_otp', models.CharField(max_length=20, null=True)),
                ('store_image', models.FileField(null=True, upload_to='images/store-images/')),
                ('store_address', models.TextField()),
                ('store_status', models.CharField(choices=[('a', 'Accepted'), ('d', 'Declined'), ('p', 'Pending')], default='p', max_length=1)),
                ('store_rating', models.FloatField(default=-1.0)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.city')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'store',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('product_description', models.TextField()),
                ('product_image', models.FileField(null=True, upload_to='images/product-images/')),
                ('product_price', models.CharField(max_length=80)),
                ('product_offer', models.CharField(max_length=80)),
                ('product_new_price', models.CharField(max_length=80)),
                ('product_status', models.CharField(choices=[('a', 'Accepted'), ('d', 'Declined'), ('p', 'Pending')], default='p', max_length=1)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
                'db_table': 'product',
            },
        ),
    ]
