# Generated by Django 4.0.2 on 2023-02-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_mobile', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_password', models.CharField(max_length=50)),
                ('client_otp', models.CharField(max_length=10, null=True)),
                ('client_address', models.TextField()),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.city')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'client',
                'db_table': 'client',
            },
        ),
    ]
