# Generated by Django 4.0.2 on 2023-02-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_category_image'),
        ('client', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('order_date', models.DateField(null=True)),
                ('payment_mtd', models.CharField(choices=[('o', 'Online'), ('c', 'COD')], default='c', max_length=1)),
                ('order_status', models.CharField(choices=[('p', 'Processing'), ('d', 'Delivered')], default='p', max_length=1)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
                ('item_total_price', models.CharField(max_length=50)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'verbose_name': 'orderDetails',
                'verbose_name_plural': 'orderDetails',
                'db_table': 'orderDetails',
            },
        ),
    ]
