# Generated by Django 4.0.2 on 2023-02-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_order_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Store',
        ),
    ]
