# Generated by Django 4.0.2 on 2023-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order_delivery_status',
            field=models.CharField(choices=[('p', 'Processing'), ('d', 'Delivered')], default='p', max_length=1),
        ),
    ]
