# Generated by Django 4.0.2 on 2023-02-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_orderdetails_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
    ]
