# Generated by Django 4.0.2 on 2023-02-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_category_image'),
        ('client', '0006_orderdetails_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(null=True)),
                ('review_score', models.IntegerField()),
                ('review_title', models.CharField(default='No Experience Shared', max_length=100)),
                ('review_description', models.TextField(default='No Additional Information')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'review',
                'db_table': 'review',
            },
        ),
    ]
